### ISSUE TITLE
HSOverlay self is not defined (Nextjs 14 + preline 2 + @preline/overlay plugin)

### ISSUE THREAD

**Issue by dieg092** [htmlstreamofficial/preline#198]
Im using Overlay plugin (@preline/overlay), it works fine (open and close succesfull), but when i want to force open or close with HSOverlay i get webpack error (it works fine, but error is shown in Visual Studio Code console). 

If i comment `HSOverlay.close(element)` line, the error disappear. I would like fix it. Thanks.

Error:
` ⨯ node_modules/@preline/overlay/index.js (2:223) @ self
 ⨯ ReferenceError: self is not defined
    at __webpack_require__ (/Users/diego/Projects/reviviendo-map/.next/server/webpack-runtime.js:33:42)
    at eval (./src/ui/components/utils/modals/Modal.tsx:11:74)
    at (ssr)/./src/ui/components/utils/modals/Modal.tsx (/Users/diego/Projects/reviviendo-map/.next/server/app/(admin)/(super)/pueblos/[id]/page.js:667:1)
    at __webpack_require__ (/Users/diego/Projects/reviviendo-map/.next/server/webpack-runtime.js:33:42)
    at eval (pueblos/[id]/page.tsx:9:91)
    at (ssr)/./src/app/(admin)/(super)/pueblos/[id]/page.tsx (/Users/diego/Projects/reviviendo-map/.next/server/app/(admin)/(super)/pueblos/[id]/page.js:172:1)
    at __webpack_require__ (/Users/diego/Projects/reviviendo-map/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)`

Component:
`'use client'
import HSOverlay from '@preline/overlay'
...

const Modal: React.FC<ModalProps> = ({
}) => {
    const [actionSelected, setActionSelected] = useState<string>('')

    const closeModal = () => {
        const element = document.querySelector('#' + id) as HTMLElement;

        if (typeof HSOverlay !== 'undefined' && HSOverlay && HSOverlay.close) {
            HSOverlay.close(element); 
        }
    }
    
   ...
}

export default Modal`

PrelineScript:
`'use client'

import { usePathname } from 'next/navigation'
import { useEffect } from 'react'

export default function Preline() {
    const path = usePathname()

    useEffect(() => {
        import('preline/preline')
    }, [])

    useEffect(() => {
        setTimeout(() => {
            // @ts-ignore
            HSStaticMethods.autoInit()

        }, 100)
    }, [path])

    return null
}`

RootLayout:
`imports ...

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="es" suppressHydrationWarning>
            <body className={inter.className + ' dark:bg-slate-900'}>
                <Providers>
                    <TopNav />
                    <main className="" id="content" role="main">
                        {children}
                    </main>
                </Providers>
            </body>
            
            <Preline /> 
        </html>
    )
}
`
packages:
` "@preline/overlay": "^2.0.1",
    "next": "^14.0.1",
    "preline": "^2.0.2",
    "react": "^18",
    "react-dom": "^18",
    ...`

**Comment by dieg092** [comment]
Testing some thinks i found this way (Dynamic import) that fix the error:

```
// import HSOverlay from '@preline/overlay';  // <--------- Not import on top

const isBrowser = typeof window !== 'undefined'  // <---------- Get if is Browser

const Modal: React.FC<ModalProps> = ({ }) => {
    const closeModal = () => {
        const element = document.querySelector('#' + id) as HTMLElement

        if (isBrowser) {
            import('@preline/overlay').then((overlay) => {  // <----------- Import if is browser
                const { HSOverlay } = overlay

                HSOverlay.close(element)
            })
        }
    }

export default Modal;
```

Please, tell me if you know better ways to fix it, thanks!

**Comment by VishalLudhrani** [comment]
The workaround that you mentioned works perfectly fine.
So why are you looking for other ways to fix it?

**Comment by dieg092** [comment]
Simply to improve the code if possible, I don't usually import libraries in this way

**Comment by astro-jets** [comment]
My code runs fine but sometimes when I want to load a page I get an error:

**Comment by astro-jets** [comment]
My code runs fine, but sometimes when I want to load a page, I get an a ReferenceError: HSStaticMethods is not defined. `<br/>`
![Uploading Screenshot (343).png…]() `<br/><br/>`
Here is my code `<br/>`
![Screenshot (344)](https://github.com/htmlstreamofficial/preline/assets/56735059/01757059-5684-4e51-838d-a9a3147bc4bb)

**Comment by astro-jets** [comment]
My code runs fine, but sometimes when I want to load a page, I get an a ReferenceError: HSStaticMethods is not defined. 
![Screenshot (343)](https://github.com/htmlstreamofficial/preline/assets/56735059/99d9ac16-54ec-415f-ae6a-cce9a457be73)

Here is my code 
![Screenshot (344)](https://github.com/htmlstreamofficial/preline/assets/56735059/248cfb5f-ef1e-4227-850b-e6489d68d794)

**Comment by astro-jets** [comment]
I am not sure but here is how I included the preline script:
 [image: image.png]

**Comment by Fintasys** [comment]
I have the same issue, is there any proper documentation on how to close a Modal within a method?
