### ISSUE TITLE
Vue: autoInit fires error upon App mount

### ISSUE THREAD

**Issue by RSchmitzHH** [htmlstreamofficial/preline#491]
### Summary

The Vue installation guide advises to add a window.HSStaticMethods.autoInit(); to the onMounted() of the basic App.vue. However, this fires an error at l. 152

### Steps to Reproduce

Following the preline Vue installation notes at [https://preline.co/docs/frameworks-vuejs.html](), I added 

```onMounted(() => {
  setTimeout(() => {
    window.HSStaticMethods.autoInit();
  }, 100)
});
```

to `App.vue`.

However, directly at startup, this fires the following error from `preline.js, l. 152:` 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at new e (preline.js:152:992)
    at preline.js:152:2902
    at NodeList.forEach (<anonymous>)
    at e.autoInit (preline.js:152:2756)
    at preline.js:207:255
    at Array.forEach (<anonymous>)
    at Object.autoInit (preline.js:207:212)
    at App.vue:28:28
```

(cf. screenshot below)

<img width="398" alt="autoInit error" src="https://github.com/user-attachments/assets/b6b2b693-312c-41b5-8a3e-823001c2cf80">

I should be at the newest version 

```
   "@preline/accordion": "^2.5.0",
    "@preline/collapse": "^2.5.0",
    "@preline/copy-markup": "^2.5.0",
    "@preline/dropdown": "^2.5.0",
    "@preline/overlay": "^2.5.0",
    "@preline/select": "^2.5.1",
    "@preline/stepper": "^2.5.1",
    "@preline/tabs": "^2.5.0",
...
    "preline": "^2.5.1",
```

### Demo Link

N/A

### Expected Behavior

Should not fire an error

### Actual Behavior

Does fire an error

### Screenshots

<img width="398" alt="autoInit error" src="https://github.com/user-attachments/assets/fb57dcca-b0d5-434c-8814-41abbe12b749">

**Comment by arthures11** [comment]
i have the same issue, angular 
![image](https://github.com/user-attachments/assets/f84b41ab-f70c-4a77-96de-5cb8221ea1c1)

**Comment by RSchmitzHH** [comment]
Any comment by the authors? Getting all these errors right on startup is quite unsatisfactory, I must say...

**Comment by olegpix** [comment]
@RSchmitzHH 
Could you please share a link to your code? It seems like the required markup might be missing, as the error suggesting that the function can't find the needed attribute typically points to this issue.

In the meantime, you can refer to the [basic demo](https://stackblitz.com/edit/preline-v2-vue-and-vue-router) for Vue, which was created to illustrate the correct project setup.
