### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' (at preline.js:1:1)

### ISSUE THREAD

**Issue by emaduddin678** [htmlstreamofficial/preline#507]
### Summary

I am new in preline. it is awesome. In my react vite my i use a ai chat prompt. it is worknig locally fine. but in netlify I got Uncaught SyntaxError: Unexpected token '<' (at preline.js:1:1). and didn't understand why it is happening.

### Steps to Reproduce

visit this page below and you can see the console.

### Demo Link

https://jonhs-hopkins-chatbot.netlify.app/

### Expected Behavior

![image](https://github.com/user-attachments/assets/50ed0068-23a4-4ecd-899d-ab6d6be3a9f5)

### Screenshots

![image](https://github.com/user-attachments/assets/81e7aedc-3559-400f-acd0-9df4334d02d8)
![image](https://github.com/user-attachments/assets/a41bfbbc-4c9b-4ccf-a204-deab6f140f86)

**Comment by olegpix** [comment]
@emaduddin678 Hi,
It seems the issue occurs because Preline is being called before the elements it needs to initialize are available on the page. Make sure to use the appropriate application lifecycle method to initialize Preline at the right time. For guidance, please refer to our framework-specific [demos](https://stackblitz.com/@jahaganiev).
